#!/bin/sh

# A script mvn clean recursively.

list_alldir(){  
    for file2 in `ls $1`  
        do  
            if [ x"$file2" != x"." -a x"$file2" != x".."  ];then  
                if [ -d "$1/$file2"  ];then  
                    cd "$1/$file2"  
                    echo "Entering $1/$file2........."  
                    if [ -f pom.xml ];then
                        mvn clean
                    else
                        echo 'no pom here'
                        list_alldir .
                    fi
                    cd ..
                fi  
             fi  
        done  
}  
if [ -f "pom.xml" ];then
    mvn clean
else
    list_alldir .
fi
